name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: textarea
    id: desc
    attributes:
      label: What happened?
      description: Clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      value: |
        1.
        2.
        3.
  - type: input
    id: env
    attributes:
      label: Environment
      description: Browser + version, OS
  - type: textarea
    id: logs
    attributes:
      label: Console logs / screenshots
