name: Feature request
description: Suggest an enhancement
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Why?
      description: User value / problem solved
  - type: textarea
    id: details
    attributes:
      label: Details / mockups
